# VHDL style guide configuration file.
# https://github.com/jeremiah-c-leary/vhdl-style-guide
rule:
    global:
        indentSize: 2
    # Disable uppercase entity name
    entity_008:
        disable: true
    entity_012:
        disable: true
    architecture_014:
        disable: true
    # Disable uppercase port name
    port_010:
        disable: true
    # Disable uppercase architecture name
    architecture_011:
        disable: true
    architecture_013:
        disable: true
    # Disable Use 'event for clocks
    process_029:
        disable: true
    # Disable Enclose boolean expression in ()'s
    if_002:
        disable: true
    # Allow default assignment in port declaration
    port_012:
        disable: true
    # Allow constants to be uppercase
    constant_004:
        disable: true
    # Allow lowercase process label
    process_017:
        disable: true
    process_019:
        disable: true
    # Allow lowercase generate label
    generate_005:
        disable: true
    generate_012:
        disable: true
    # Allow lowercase for loop label
    for_loop_003:
        disable: true
    # Generics must start with G_
    generic_020:
        disable: false
